[platformio]
default_envs = sample

[env]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps = adafruit/Adafruit NeoPixel@^1.12.5

[env:sample]
build_flags =
  -D DISPLAY_WIDTH=5
  -D DISPLAY_HEIGHT=7
  -D F30_DATA_PIN=6
  -D SERIAL_BAUD=115200

[env:wall]
build_flags =
  -D DISPLAY_WIDTH=35
  -D DISPLAY_HEIGHT=21
  -D F30_DATA_PIN=6
  -D SERIAL_BAUD=115200
