[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
lib_deps = adafruit/Adafruit NeoPixel@^1.12.5
build_flags =
  -D DISPLAY_BYTES=35
  -D F30_DATA_PIN=18
