[platformio]
default_envs = sample

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
lib_deps = adafruit/Adafruit NeoPixel@^1.12.5

[env:sample]
build_flags =
  -D DISPLAY_WIDTH=5
  -D DISPLAY_HEIGHT=7
  -D F30_DATA_PIN=18

[env:wall]
build_flags =
  -D DISPLAY_WIDTH=35
  -D DISPLAY_HEIGHT=21
  -D F30_DATA_PIN=18
